org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
forge_version=47.3.0
mappings_channel=official
mappings_version=1.20.1

jei_version=15.20.0.130

mod_id=infinitestats
mod_name=infinite_stats-无限加点
mod_version=1.8.0
mod_authors=佚名既无名
mod_description=Terraria-style infinite stat point allocation system. Level up by killing mobs and allocate points to attack, defense, mobility, utility, and magic stats!
